#!/bin/bash

# Build docker image
git clone https://github.com/bakster/dokku-redis-dockerfiles /tmp/dokku-redis-dockerfiles
docker build -q=true -t luxifer/redis /tmp/dokku-redis-dockerfiles
rm -rf /tmp/dokku-redis-dockerfiles
